import {
  Player,
  Rival,
  Field,
  Competition,
  MatchWithRival,
  PlayerStatsSummary,
} from "./supabase/types";

export const initialCompetitions: Competition[] = [
  {
    id: "competition-1",
    name: "Liga Apertura Fútbol 7",
    type: "liga",
    created_at: new Date().toISOString(),
  },
  {
    id: "competition-2",
    name: "Copa de Primavera",
    type: "copa",
    created_at: new Date().toISOString(),
  },
  {
    id: "competition-3",
    name: "Torneo Amistoso Pretemporada",
    type: "amistoso",
    created_at: new Date().toISOString(),
  },
];

export const initialFields: Field[] = [
  {
    id: "field-1",
    name: "Campo Municipal El Ferial",
    address: "Calle de los Deportes 14, Madrid",
    maps_url: "https://maps.google.com/?q=Campo+Municipal+El+Ferial",
    created_at: new Date().toISOString(),
  },
  {
    id: "field-2",
    name: "Polideportivo San Juan",
    address: "Av. de la Paz s/n, Madrid",
    maps_url: "https://maps.google.com/?q=Polideportivo+San+Juan",
    created_at: new Date().toISOString(),
  },
  {
    id: "field-3",
    name: "Complejo Deportivo Las Palmeras",
    address: "Calle Olivo 22, Madrid",
    maps_url: "https://maps.google.com/?q=Complejo+Deportivo+Las+Palmeras",
    created_at: new Date().toISOString(),
  },
];

export const initialRivals: Rival[] = [
  {
    id: "rival-1",
    name: "Barrio Norte F7",
    shield_url:
      "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=128&auto=format&fit=crop&q=80",
    created_at: new Date().toISOString(),
  },
  {
    id: "rival-2",
    name: "Los Halcones FC",
    shield_url:
      "https://images.unsplash.com/photo-1518091043644-c1d4457512c6?w=128&auto=format&fit=crop&q=80",
    created_at: new Date().toISOString(),
  },
  {
    id: "rival-3",
    name: "Atlético San Juan",
    shield_url:
      "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=128&auto=format&fit=crop&q=80",
    created_at: new Date().toISOString(),
  },
  {
    id: "rival-4",
    name: "Inter Ribera",
    shield_url:
      "https://images.unsplash.com/photo-1511886929837-354d827aae26?w=128&auto=format&fit=crop&q=80",
    created_at: new Date().toISOString(),
  },
  {
    id: "rival-5",
    name: "Recreativo Olivo",
    shield_url:
      "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=128&auto=format&fit=crop&q=80",
    created_at: new Date().toISOString(),
  },
];

export const initialPlayers: Player[] = [
  {
    id: "player-1",
    first_name: "Álvaro",
    last_name: "Ramos",
    nickname: "El Muro",
    dorsal: 1,
    position: "portero",
    photo_url:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80, https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=500&auto=format&fit=crop&q=80, https://images.unsplash.com/photo-1518091043644-c1d4457512c6?w=500&auto=format&fit=crop&q=80",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "player-2",
    first_name: "Sergio",
    last_name: "García",
    nickname: "Checho",
    dorsal: 13,
    position: "portero",
    photo_url:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "player-3",
    first_name: "Carlos",
    last_name: "López",
    nickname: "Kaiser",
    dorsal: 3,
    position: "defensa",
    photo_url:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=80, https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=500&auto=format&fit=crop&q=80",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "player-4",
    first_name: "David",
    last_name: "Fernández",
    nickname: "Torre",
    dorsal: 4,
    position: "defensa",
    photo_url:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=500&auto=format&fit=crop&q=80",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "player-5",
    first_name: "Mateo",
    last_name: "Ruiz",
    nickname: "Tano",
    dorsal: 5,
    position: "defensa",
    photo_url:
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=500&auto=format&fit=crop&q=80",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "player-6",
    first_name: "Javier",
    last_name: "Martínez",
    nickname: "Mago",
    dorsal: 8,
    position: "medio",
    photo_url:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&auto=format&fit=crop&q=80, https://images.unsplash.com/photo-1511886929837-354d827aae26?w=500&auto=format&fit=crop&q=80, https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=500&auto=format&fit=crop&q=80",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "player-7",
    first_name: "Marcos",
    last_name: "Navarro",
    nickname: "Pulmón",
    dorsal: 6,
    position: "medio",
    photo_url:
      "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=500&auto=format&fit=crop&q=80",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "player-8",
    first_name: "Alejandro",
    last_name: "Sánchez",
    nickname: "Charly",
    dorsal: 10,
    position: "medio",
    photo_url:
      "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=500&auto=format&fit=crop&q=80, https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=500&auto=format&fit=crop&q=80",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "player-9",
    first_name: "Lucas",
    last_name: "Pérez",
    nickname: "Pistolero",
    dorsal: 9,
    position: "delantero",
    photo_url:
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&auto=format&fit=crop&q=80, https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=500&auto=format&fit=crop&q=80",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "player-10",
    first_name: "Daniel",
    last_name: "Gómez",
    nickname: "Rayo",
    dorsal: 7,
    position: "delantero",
    photo_url:
      "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=500&auto=format&fit=crop&q=80, https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=500&auto=format&fit=crop&q=80, https://images.unsplash.com/photo-1518091043644-c1d4457512c6?w=500&auto=format&fit=crop&q=80",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "player-11",
    first_name: "Gonzalo",
    last_name: "Castro",
    nickname: "Tanque",
    dorsal: 11,
    position: "delantero",
    photo_url:
      "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=500&auto=format&fit=crop&q=80",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "player-12",
    first_name: "David",
    last_name: "Guerrero",
    nickname: "Míster",
    dorsal: 0,
    position: "entrenador",
    photo_url:
      "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=500&auto=format&fit=crop&q=80",
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "player-13",
    first_name: "Manuel",
    last_name: "Torres",
    nickname: "Manu",
    dorsal: 0,
    position: "utillero",
    photo_url:
      "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=500&auto=format&fit=crop&q=80",
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const initialMatches: MatchWithRival[] = [
  {
    id: "match-1",
    rival_id: "rival-1",
    field_id: "field-1",
    competition_id: "competition-1",
    is_home: true,
    match_date: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    competition: "liga",
    psg_score: 4,
    rival_score: 2,
    is_finished: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    rival: initialRivals[0],
    field: initialFields[0],
    competition_ref: initialCompetitions[0],
  },
  {
    id: "match-2",
    rival_id: "rival-2",
    field_id: "field-2",
    competition_id: "competition-1",
    is_home: false,
    match_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    competition: "liga",
    psg_score: 3,
    rival_score: 0,
    is_finished: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    rival: initialRivals[1],
    field: initialFields[1],
    competition_ref: initialCompetitions[0],
  },
  {
    id: "match-3",
    rival_id: "rival-3",
    field_id: "field-1",
    competition_id: "competition-1",
    is_home: true,
    // Next upcoming match in 3 days 18:00
    match_date: new Date(
      Date.now() + 3 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000
    ).toISOString(),
    competition: "liga",
    psg_score: null,
    rival_score: null,
    is_finished: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    rival: initialRivals[2],
    field: initialFields[0],
    competition_ref: initialCompetitions[0],
  },
  {
    id: "match-4",
    rival_id: "rival-4",
    field_id: "field-3",
    competition_id: "competition-2",
    is_home: false,
    match_date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString(),
    competition: "copa",
    psg_score: null,
    rival_score: null,
    is_finished: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    rival: initialRivals[3],
    field: initialFields[2],
    competition_ref: initialCompetitions[1],
  },
];

export const initialStatsSummary: PlayerStatsSummary[] = [
  {
    player_id: "player-1",
    first_name: "Álvaro",
    last_name: "Ramos",
    nickname: "El Muro",
    dorsal: 1,
    position: "portero",
    photo_url:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&auto=format&fit=crop&q=80, https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=500&auto=format&fit=crop&q=80, https://images.unsplash.com/photo-1518091043644-c1d4457512c6?w=500&auto=format&fit=crop&q=80",
    is_active: true,
    matches_played: 2,
    total_goals: 0,
    total_assists: 0,
    total_yellow_cards: 0,
    total_red_cards: 0,
    total_clean_sheets: 1,
    goals_conceded: 2,
  },
  {
    player_id: "player-2",
    first_name: "Sergio",
    last_name: "García",
    nickname: "Checho",
    dorsal: 13,
    position: "portero",
    photo_url:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80",
    is_active: true,
    matches_played: 0,
    total_goals: 0,
    total_assists: 0,
    total_yellow_cards: 0,
    total_red_cards: 0,
    total_clean_sheets: 0,
    goals_conceded: 0,
  },
  {
    player_id: "player-3",
    first_name: "Carlos",
    last_name: "López",
    nickname: "Kaiser",
    dorsal: 3,
    position: "defensa",
    photo_url:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=80, https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=500&auto=format&fit=crop&q=80",
    is_active: true,
    matches_played: 2,
    total_goals: 0,
    total_assists: 0,
    total_yellow_cards: 1,
    total_red_cards: 0,
    total_clean_sheets: 0,
    goals_conceded: 0,
  },
  {
    player_id: "player-4",
    first_name: "David",
    last_name: "Fernández",
    nickname: "Torre",
    dorsal: 4,
    position: "defensa",
    photo_url:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=500&auto=format&fit=crop&q=80",
    is_active: true,
    matches_played: 1,
    total_goals: 0,
    total_assists: 1,
    total_yellow_cards: 0,
    total_red_cards: 0,
    total_clean_sheets: 0,
    goals_conceded: 0,
  },
  {
    player_id: "player-5",
    first_name: "Mateo",
    last_name: "Ruiz",
    nickname: "Tano",
    dorsal: 5,
    position: "defensa",
    photo_url:
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=500&auto=format&fit=crop&q=80",
    is_active: true,
    matches_played: 1,
    total_goals: 1,
    total_assists: 0,
    total_yellow_cards: 0,
    total_red_cards: 0,
    total_clean_sheets: 0,
    goals_conceded: 0,
  },
  {
    player_id: "player-6",
    first_name: "Javier",
    last_name: "Martínez",
    nickname: "Mago",
    dorsal: 8,
    position: "medio",
    photo_url:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&auto=format&fit=crop&q=80, https://images.unsplash.com/photo-1511886929837-354d827aae26?w=500&auto=format&fit=crop&q=80, https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=500&auto=format&fit=crop&q=80",
    is_active: true,
    matches_played: 2,
    total_goals: 1,
    total_assists: 3,
    total_yellow_cards: 0,
    total_red_cards: 0,
    total_clean_sheets: 0,
    goals_conceded: 0,
  },
  {
    player_id: "player-7",
    first_name: "Marcos",
    last_name: "Navarro",
    nickname: "Pulmón",
    dorsal: 6,
    position: "medio",
    photo_url:
      "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=500&auto=format&fit=crop&q=80",
    is_active: true,
    matches_played: 1,
    total_goals: 0,
    total_assists: 0,
    total_yellow_cards: 0,
    total_red_cards: 0,
    total_clean_sheets: 0,
    goals_conceded: 0,
  },
  {
    player_id: "player-8",
    first_name: "Alejandro",
    last_name: "Sánchez",
    nickname: "Charly",
    dorsal: 10,
    position: "medio",
    photo_url:
      "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=500&auto=format&fit=crop&q=80, https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=500&auto=format&fit=crop&q=80",
    is_active: true,
    matches_played: 1,
    total_goals: 0,
    total_assists: 1,
    total_yellow_cards: 1,
    total_red_cards: 0,
    total_clean_sheets: 0,
    goals_conceded: 0,
  },
  {
    player_id: "player-9",
    first_name: "Lucas",
    last_name: "Pérez",
    nickname: "Pistolero",
    dorsal: 9,
    position: "delantero",
    photo_url:
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&auto=format&fit=crop&q=80, https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=500&auto=format&fit=crop&q=80",
    is_active: true,
    matches_played: 2,
    total_goals: 4,
    total_assists: 0,
    total_yellow_cards: 0,
    total_red_cards: 0,
    total_clean_sheets: 0,
    goals_conceded: 0,
  },
  {
    player_id: "player-10",
    first_name: "Daniel",
    last_name: "Gómez",
    nickname: "Rayo",
    dorsal: 7,
    position: "delantero",
    photo_url:
      "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=500&auto=format&fit=crop&q=80, https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=500&auto=format&fit=crop&q=80, https://images.unsplash.com/photo-1518091043644-c1d4457512c6?w=500&auto=format&fit=crop&q=80",
    is_active: true,
    matches_played: 1,
    total_goals: 1,
    total_assists: 1,
    total_yellow_cards: 0,
    total_red_cards: 0,
    total_clean_sheets: 0,
    goals_conceded: 0,
  },
  {
    player_id: "player-11",
    first_name: "Gonzalo",
    last_name: "Castro",
    nickname: "Tanque",
    dorsal: 11,
    position: "delantero",
    photo_url:
      "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=500&auto=format&fit=crop&q=80",
    is_active: true,
    matches_played: 1,
    total_goals: 0,
    total_assists: 1,
    total_yellow_cards: 0,
    total_red_cards: 0,
    total_clean_sheets: 0,
    goals_conceded: 0,
  },
  {
    player_id: "player-12",
    first_name: "David",
    last_name: "Guerrero",
    nickname: "Míster",
    dorsal: 0,
    position: "entrenador",
    photo_url:
      "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=500&auto=format&fit=crop&q=80",
    is_active: true,
    matches_played: 2,
    total_goals: 0,
    total_assists: 0,
    total_yellow_cards: 0,
    total_red_cards: 0,
    total_clean_sheets: 0,
    goals_conceded: 0,
  },
  {
    player_id: "player-13",
    first_name: "Manuel",
    last_name: "Torres",
    nickname: "Manu",
    dorsal: 0,
    position: "utillero",
    photo_url:
      "https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=500&auto=format&fit=crop&q=80",
    is_active: true,
    matches_played: 2,
    total_goals: 0,
    total_assists: 0,
    total_yellow_cards: 0,
    total_red_cards: 0,
    total_clean_sheets: 0,
    goals_conceded: 0,
  },
];
